# directory: 'raw_dataset'
directory: 'toronto_raw_dataset'
# directory: 'fake_raw_dataset'

# Set pretrained True for transfer learning?
# pretrained: True
pretrained: False
# pretrained_weights_path: "Output_Files/efficient_net_20210124/output_folder_combined_0.001_None_raw_dataset_5/model_weights/model_weights.h5"
pretrained_weights_path: "Output_Files/efficient_net_transfer_learning/output_folder_combined_0.001_None_raw_dataset_5/model_weights/model_weights.h5"

# directory: 'raw_dataset'

CNN_model: 'RegNet'
dense_model:
  - 8
  - 4
optimizer: 'Adam'
LR_scheduler: 'None'
init_lr: 'None'
momentum: 0.1
weight_decay: 0.1
learning_rate: 0.0001
learning_rates: [0.001]
beta: 0.7
mini_batch_size: 16
loss_function: "mean_absolute_percentage_error"
number_of_epochs: 50
image_height: 150
image_width: 150
# 224 for EfficientNet (as recommended by PhD dude #2)
CNN_input_shape: [224, 224, 3]
train_val_test_ratio: [0.85,0.14,0.01]
augmentation_multiplier: 2
import_mode: 'False'
# import_mode: 'True'
